
-- Total revenue generated by male vs female customers
SELECT gender, sum(purchase_amount) as revenue
From customers
GROUP by gender;

-- Which customers used discount but still spent more than the average purchase amount
SELECT customer_id, purchase_amount
FROM customers
WHERE discount_applied = 'YES' AND purchase_amount >= (SELECT avg(purchase_amount));

-- Which are the top 5 products with the highest average review ratings
SELECT item_purchased,
ROUND(AVG(review_rating)) as "Average Product rating"
FROM customers
group by item_purchased
order by AVG(review_rating) DESC
limit 5;

--  Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(AVG(purchase_amount),2)
From customers
WHERE shipping_type='Standard' OR shipping_type='Express'  -- shipping_type in ('Standard','Express')
group by shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount), 2) AS avg_spend,
round(SUM(purchase_amount),2) As total_revenue
FROM customers
GROUP BY subscription_status
order by total_revenue;

-- Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
ROUND(
    100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
    / COUNT(discount_applied),
2) AS discount_rate
FROM customers
group by item_purchased
order by discount_rate DESC
LIMIT 5;


-- Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
With customer_type as (
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases =1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
    FROM customers )
SELECT customer_segment, 
count(*) AS 'Number of Customers'
FROM customer_type
group by customer_segment;
    

-- top 3 most purchased products within each category? 
WITH item_count AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)

SELECT 
    item_rank, category, item_purchased, total_orders
FROM item_count
WHERE item_rank <= 3;


-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, 
count(customer_id) as repeated_buyers
FROM customers
WHERE previous_purchases >5
GROUP by subscription_status;

-- What is the revenue contribution of each age group? 
SELECT age_group,
SUM(purchase_amount) as total_revenue
FROM customers
group by age_group
order by total_revenue DESC;


